### ISSUE TITLE
Filtering for older game versions

### ISSUE THREAD

**Issue by mweinelt** [ajour/ajour#486]
**Is your feature request related to a problem? Please describe.**
A general problem with playing on private servers is that they're on older game versions like 1.12.0, 2.4.3, 3.3.5, 4.3.4, 5.4.7 and so on. It is unnecessarily tedious to find, download and install or, more generally, manage addons for these versions.

**Describe the solution you'd like**
If Ajour would allow for selecting a game version and then filtering its catalog by it, that would be a great boon to all players on private servers.

**Describe alternatives you've considered**
Manually browsing websites for compatible versions.

**Additional context**
The catalogs already contain the required information, so I feel this is pretty close. Nice work!

P.S.: I've packaged up Ajour for nixpkgs (the [NixOS](https://nixos.org) package collection) over at https://github.com/NixOS/nixpkgs/pull/108738. We're just sorting through the latest issues before it will be merged.

**Comment by tarkah** [comment]
Thanks for the feature request! We've had this requested in our Discord chat as well. A couple thoughts:

- The "game version" in the catalog is based off the latest release. Meaning that if we filter on "5.4.7" for example, it'll only show addons that haven't been updated in years vs "older versions" of all addons in the catalog.
- I assume you'd want to see the "older versions" of all the top / popular addons and not just "unmaintained since X version" addons

I'd hate to implement a filter on this without fixing the root need, which is to show ALL addons, but using the release "<=" the supplied version filter. Unfortunately our catalog doesn't have this information and only has info around the "latest release". 

We don't have a "catalog API" that we dynamically query based off parameters and returning paginated results. We transmit the ENTIRE catalog when Ajour is opened, so that the catalog is extremely responsive. As you can imagine, storing information about EVERY release in that catalog file will make it way too big to transport over internet (it's already slow for a lot of users as is).

This means we'd have to build and host an API so we can dynamically send this catalog data / handle the filter we're talking about. I'm not sure that's ever going to be in scope for Ajour, but I'd love @casperstorm view on the topic. Otherwise we can implement a basic filter on the current catalog's "game version" field that we have, but I can't imagine this will be very helpful in reality as you'll only see super old / unmaintained addons and will exclude all the top addons that exited back then, but have had releases since.

**Comment by tarkah** [comment]
Also, thanks for the efforts packaging this for NixOS! I've used Nix in the past and it's a really cool way of doing things. Packaging is a huge deal, so thank you! Once you get things published, feel free to open a PR adding it to our INSTALL.md file.

**Comment by mweinelt** [comment]
Ah yeah, that is something I missed while skimming the catalog, that addons, that are still maintained would have no older version, that matches the required version. I'm not quite sure how much more expensive this would make the catalog creation.

To limit the scope somewhat, we wouldn't need *all* patch versions, as most are unlikely to ever be used. Popular ones are the last versions of each expansion (1.12.0, 2.4.3, 3.3.5, 4.3.4, 5.4.7, 6.2.4, 7.3.5, 8.3.7), with 3.3.5 being the most well supported (from the emu perspective) and most available ones.
