### ISSUE TITLE
Search broken?

### ISSUE THREAD

**Issue by Dreamjammer** [ajour/ajour#517]
The search function in 0.7 seems to be broken. For example, searching for "minimap" fails to show some minimap-related addons, including some that have "Minimap" right in the name! e.g. BasicMinimap.

**Comment by casperstorm** [comment]
@tarkah can you take a look at this?

**Comment by tarkah** [comment]
@Dreamjammer It does in fact appear in the results, but you have to change # results to 50 to see it. The reason it's below other results that seem to be a worse match, is because they also have "minimap" in the description (we use title and description to fuzzy search) and they are getting identical scores. When match scores are identical, it defaults to sorting by # Downloads.

There is a bonus we can apply in the fuzzy match for words that are camelCase that match the search  term. However, when I tweak this, it has unintended results for other types of searches where its now ranking things higher that shouldn't be. I could not find any other settings to tweak to score BasicMinimap better than the other few items its scoring the same against when searching "minimap".

**Comment by Dreamjammer** [comment]
Seems to me a title match should maybe score higher than a description match?

**Comment by Dreamjammer** [comment]
Also, maybe at a setting to make the new "fuzzy" search optional? I switched from WowUp to Ajour precisely because the search seemed to work a lot better. Now, it seems to be just as bad as WowUp's... however it worked before, it definitely worked better for me, bringing precisely what I was looking for close to the top consistently.

Granted, maybe the new search works better if you don't know what you're searching for and just browsing, but it seems to make finding that one addon you half-remember the name of but don't know exactly a lot harder (in my case a couple months ago, I knew "minimap" was in the name, but couldn't remember whether it was "simple", "basic", or whatnot -- when I couldn't find it in WowUp, I tried Ajour and it popped right up... but not anymore...) And this is my usual search case -- someone mentioned an addon during a stream or something and I half-remember the name. There are plenty of times I'd love to just disable searching the descriptions, just show me what has a particular substring in the name. Of course, other times searching descriptions is nice. It would be cool to have some options here...

**Comment by tarkah** [comment]
@Dreamjammer Completely agree on title vs description. Can you test out #523? I score title and description separately now, and halve the score of description, then take the max score between the two instead of calculating a single score on the concatenation of those two string. This seems to help keep the results with matches in the title sorted first. Of course BasicMinimap still appears past result 25 :P But that's because so many addons have "Minimap" as a standalone word in the title. At least now things like "Gatherer2" aren't sorted above it by default due to the description match.

**Comment by Dreamjammer** [comment]
> @Dreamjammer Of course BasicMinimap still appears past result 25 :P But that's because so many addons have "Minimap" as a standalone word in the title. At least now things like "Gatherer2" aren't sorted above it by default due to the description match.

That's cool -- if there are more than 25 addons with the string I'm looking for in the title, I'd know get more results and look further down; it's just when it appears to run out of them on a page that it wouldn't occur to me to look further. So this sounds like it would fix the issue.

Is there an easy way to test this prior to it becoming part of a release? If not, I'll just check as soon as the client next updates itself.

**Comment by tarkah** [comment]
I've just merged this into the development branch, so it should be available as part of our next beta release. You can make sure your client checks for self updates against that beta channel by selecting it in the settings.
