### ISSUE TITLE
Ajour should be able to optionally search addon descriptions

### ISSUE THREAD

**Issue by Kream** [ajour/ajour#539]
**Is your feature request related to a problem? Please describe.**
I'm frustrated when I don't know the name of the a particular addon so I can download it. I have to search via google or forums. This is most prominent when, for example, an addon has a name that has nothing to do with the function of the Addon, for example, "Masque" or "Carbonite" or "Prat". This is despite the fact that those addon descriptions would contain the phrases " 'button' or 'skin'", "world map" or "chat", respectively.

**Describe the solution you'd like**
I would like Ajour to incorporate functionality whereby it is possible to search within addon descriptions as well, ideally so that if required we can choose to search within descriptions and notes alone or within titles alone or within titles, descriptions and notes.

**Describe alternatives you've considered**
Googling for links to various forums. Inefficient, inaccurate and timeconsuming. 

**Additional context**
I am really impressed by how good Ajour has become in such a short time. Thank you.

**Comment by tarkah** [comment]
@Kream thanks for opening the issue! We actually do search on both addon name and description for the catalog fuzzy search. We are scoring the description matches lower than the title matches, which might be why the results you're expecting to see at the top are a bit further down in the results.

For example, when I search "button", and I increase the # of results to 100, "Masque" shows up near the bottom. Because so many addons have "button" in the title, it just gets lost in the noise of all the search results. Nothing we can really do there due.

One thing that I recommend doing, is after searching a generic term, sort the results by # Downloads or Latest Release. These are typically the more popular / active addons that match you search term and probably more relevant. "Masque" is the second result when I search "button" and sort by # Downloads.
