### ISSUE TITLE
Add a "Restore backup" option

### ISSUE THREAD

**Issue by NathanCrama** [ajour/ajour#542]
**Is your feature request related to a problem? Please describe.**
Ajour already offers an easy-to-use backup system, but no way to restore backups, which has to be done manually.

**Describe the solution you'd like**
It would be great to have a button to automatically unzip and restore the latest backup found.

**Describe alternatives you've considered**
Other approaces include a file picker to let us choose which archive to restore, or a picker in the client itself which could show the date/time of the backups found in the selected backup folder.

**Additional context**
/

**Comment by mlablah** [comment]
@NathanCrama Thank you for suggesting feature. 

We have considered adding the ability to restore from backup to Ajour, but we decided against it for a few reasons. The biggest reason being that restoring user data from a backup can be a very delicate operation and we risk destroying (or allowing the user to inadvertently destroy) his/her data.

For example, the user might want to restore only part of what the backup contains. A handful of addons, or the SavedVariables associated with a single character on a single realm. 
Or the user might think that restoring the backup will only restore something that was lost. Not realizing all the things that would also be rolled back in the process.

On the other hand, we think that designing the UI required to allow for a fine-grained control of what to restore from the backup is beyond the scope of an addon manager, 

And so we decided that restoring from the backup is best left to the user, by manually choosing what to extract from the zip file, instead of offering an all-or-nothing restore feature.
