### ISSUE TITLE
A certain addon is not shown in the application

### ISSUE THREAD

**Issue by RENgOLD** [ajour/ajour#567]
**Describe the bug**
Addon ["Grounded"](https://www.curseforge.com/wow/addons/grounded) for Classic WoW not present it Catalog (cant find by name) and not shown in My Addons even when i installed it manually.
[ajour.log](https://github.com/ajour/ajour/files/6134502/ajour.log)

**Comment by casperstorm** [comment]
Thanks for reporting.

Reason it is not showing in in classic catalog is because the author has listed it both as a retail and classic addon, but I think the API is failing because it is only giving us it back as retail. You can see the response here, and switch to retail catalog and find it.

```json
{
    "id": 439396,
    "websiteUrl": "https://www.curseforge.com/wow/addons/grounded",
    "dateReleased": "2021-02-16T13:33:22.917Z",
    "name": "Grounded",
    "summary": "Creates bindings to show the targeting reticle for ground-targeting spells on key down, and to cast at the cursor on key up.",
    "numberOfDownloads": 611,
    "categories": [
        "Action Bars"
    ],
    "flavors": [
        "wow_retail"
    ],
    "gameVersions": [
        {
            "flavor": "wow_retail",
            "gameVersion": "9.0.2"
        }
    ]
}
```

For now I would suggest you to install it manually. Ill investigate some more later.

**Comment by casperstorm** [comment]
It should be there now. So i'll close this issue.
