### ISSUE TITLE
Plater Nameplates Updates

### ISSUE THREAD

**Issue by Quiksmage** [ajour/ajour#580]
Hi, 
I'm not sure if I'm doing it wrong, but my nameplate updates don't seem to actually take effect. I see them as "update available" and then "completed" after I do the update, but relogging or refreshing after doing so still yields the same update. I thought it may work like weak auras and have an ingame update, but I was unable to locate it. Thanks in advance for taking a look!
![image](https://user-images.githubusercontent.com/12449533/111855015-a0b17100-88df-11eb-92ad-e00677224dd5.png)
![image](https://user-images.githubusercontent.com/12449533/111855022-ad35c980-88df-11eb-9eb8-1181491a7d8c.png)

to add, this is on 0.8.0-rc.2

**Comment by casperstorm** [comment]
I should really make a wiki entry for it, because it's not very clear what to do actually, @Quiksmage.
When you press `Update all` the WeakAuras and Plater scripts gets loaded into the game, but is not yet "applied". 

To apply a WeakAura update you switch back to the game and do `/reload` and then `/wa`. Now you'll notice a small Wago symbol on the scripts you prepared in Ajour. Press it and it will update. Plater is almost the same. Depending on if its a Profile or a Script you go to the respective tab and find the same Wago icon and press it.

Here's a picture of how the icon look in WeakAuras:
![image](https://user-images.githubusercontent.com/2248455/111875627-21817300-899b-11eb-81bd-1e7ff70c6637.png)

**Comment by Quiksmage** [comment]
Hey, thanks for the clarification on updating plater. you should also add in the following. If you have multiple plater profiles, they need to be ACTIVE for you to update them. I had previously found this area, but the update button was greyed out.
![image](https://user-images.githubusercontent.com/12449533/111882250-df900700-8971-11eb-869f-76d0d82cd204.png)
 I didn't think about swapping to the profile.

the proper steps for plater profile updating -
1. update plater profile
2. swap to the profile in game
3. reload ui
4. open /plater
5. go to profiles tab
6. click update profile
