### ISSUE TITLE
Update from 0.7.2 to 1.0.1 fails

### ISSUE THREAD

**Issue by stijnherreman** [ajour/ajour#619]
**Describe the bug**
Trying to update from 0.7.2 to 1.0.1 fails and and does not gracefully undo the update attempt. Previous automatic updates always succeeded.

**To Reproduce**
1. Open Ajour 0.7.2
2. See 'New Ajour version available 0.7.2 -> 1.0.1' and click the Update button
3. See 'Failed to update Ajour'
4. Additional attempts by clicking the 'Failed' button, fail as well

**Expected behavior**
The update either succeeds completely, or the application is reverted to its state before the update attempt.

**Screenshots**
![image](https://user-images.githubusercontent.com/1618054/114384544-21862480-9b8f-11eb-9570-903a41ad6059.png)
![image](https://user-images.githubusercontent.com/1618054/114384609-38c51200-9b8f-11eb-8f95-4883f9e6b60d.png)

**Software involved**
Please complete the following information:
 - OS: Windows 10 build 21343 (the March 24 preview build)
 - Ajour version: 0.7.2

**Log Output**
```
12:53:39.790 [ajour::gui::update][DEBUG] Interaction::UpdateAjour
12:53:39.790 [ajour_core::network][DEBUG] downloading file from https://github.com/ajour/ajour/releases/download/1.0.1/ajour.exe
12:53:42.015 [ajour_core::network][DEBUG] file saved as "C:\\Games\\World of Warcraft\\tmp_ajour.exe"
12:53:42.016 [ajour::gui::update][DEBUG] Message::AjourUpdateDownloaded
12:53:42.016 [ajour][ERROR] Failed to update Ajour
12:53:42.016 [ajour][ERROR] caused by: The process cannot access the file because it is being used by another process. (os error 32)
12:53:50.910 [ajour::gui::update][DEBUG] Interaction::UpdateAjour
12:53:50.910 [ajour_core::network][DEBUG] downloading file from https://github.com/ajour/ajour/releases/download/1.0.1/ajour.exe
12:53:52.548 [ajour_core::network][DEBUG] file saved as "C:\\Games\\World of Warcraft\\tmp_ajour.exe"
12:53:52.624 [ajour::gui::update][DEBUG] Message::AjourUpdateDownloaded
12:53:52.624 [ajour][ERROR] Failed to update Ajour
12:53:52.624 [ajour][ERROR] caused by: The system cannot find the file specified. (os error 2)
```

The log shows an initial attempt and a second attempt.

**Comment by casperstorm** [comment]
So you need to run `ajour.exe` and remove all the `tmp*_ajour.exe`.
Also, you need to make sure you run it from a place you have write permissions, %APPDATA% or your desktop.

Let me know if that helps.

**Comment by stijnherreman** [comment]
The original `ajour.exe` was gone, as seen in the second screenshot.

I do have write permissions. The process was able to download the updated version, and all other times the update mechanism worked fine.

A race condition seems plausible, but I haven't looked at the code.

**Comment by casperstorm** [comment]
So you ran `ajour.exe` initially which then later, during the update process disappeared?  Also you had a `tmp2_ajour.exe` there meanwhile? `temp2_ajour.exe` seems to be from last month.

From the logs you posted it seems like the Ajour application it tried to open (the downloaded 1.0.1) was already in use, properly because of name collision:

> 12:53:42.016 [ajour][ERROR] caused by: The process cannot access the file because it is being used by another process. (os error 32)

**Comment by tarkah** [comment]
So the way the update process works is as follows:

1. Download the newest release as `tmp_ajour`.
2. Rename the current running process as `tmp2_ajour`
3. Rename `tmp_ajour` (the new binary) to `ajour` (or whatever the original process was named, if renamed)
4. Launch `ajour` and exit current process
5. When the new `ajour` launches, it'll cleanup `tmp2_ajour` if it exists in the folder.

It's *possible* that the rename operations fail with windows due to file locks from antivirus and such. We have a retry mechanism that runs over ~30 seconds so it should succeed eventually.
