### ISSUE TITLE
UX Improvement: Mouse movement distance

### ISSUE THREAD

**Issue by mistersister** [ajour/ajour#622]
I think the Website, Changelog, Exclude and Delete buttons on your installed addons are way out of hand and requiere quite big mouse movement. This is specially frustrating when using 21:9 or high-res monitors or even with a regular 1080p monitor and Ajour in fullscreen

An easy fix would be to just move those elements right below the addon info section. Right below the release channel dropdown menu. 

See attached pic:

![Untitled](https://user-images.githubusercontent.com/3819621/114919900-1fd78d80-9e29-11eb-889f-de9ebb19bafc.png)

**Comment by casperstorm** [comment]
I like having it to the right for a few reasons. It aligns well with the other buttons, such as update, and and it creates a better overall weight when looking at it. It quickly becomes too heavy if everything was left aligned.
Another issue we had when it was left aligned was that "Delete" suddenly became something you should avoid pressing because it was right in the middle of everything.

In my humble opinion it's not a solution to gather everything to the side just because the screen is wide.
