### ISSUE TITLE
Backup-button / Settings: custom sort

### ISSUE THREAD

**Issue by behhNa** [ajour/ajour#625]
Hi,

since I use Ajour I don't do my addon backups manually anymore.
With more and more features the "Backup Now"-button is moving to the bottom on the settings panel. 
Is it possible to put the button in the top-bar? Maybe right so the "Settings"-Button?
Or, if thats not a good solution, to get a custom sorting in the settings panel? Themes and directories for example aren't changed that often, so they can be at the bottom. (In my opinion :D)

Sry for my english.
Anyways....thanks for this great updater!

**Comment by casperstorm** [comment]
I am a little confused because you say:

> since I use Ajour I don't do my addon backups manually anymore.

But then it sounds like you do in fact press it manually:

> with more and more features the "Backup Now"-button is moving to the bottom on the settings panel.

So if I understand the suggestion/question correctly you regularly go to Settings and make a backup of your addons, and you find it cluttered in there because of all the settings. If that is the case, I would suggest you to take a look at [CLI.md](https://github.com/ajour/ajour/blob/master/CLI.md). You could setup a backup automation quite easily every time you log into Windows for example. To do this you can follow  [Update addons automatically when you log in (Windows)](https://github.com/ajour/ajour/wiki/Update-addons-automatically-when-you-log-in-(Windows)) and then instead of `update` you can look at how to do backup.

From [CLI.md](https://github.com/ajour/ajour/blob/master/CLI.md):

```
# Backup both WTF and AddOns folder for all flavors

ajour backup -b both

# Backup the WTF folder for Retail

ajour backup -b wtf -f retail /tmp
```

Let me know if this could solve your issue.

**Comment by behhNa** [comment]
Thanks for the response. 
With manually I meant that I zipped my folders (interface/wtf) on my own.
