### ISSUE TITLE
Automatic daily / hourly Backups

### ISSUE THREAD

**Issue by KyleCRat** [ajour/ajour#636]
**Is your feature request related to a problem? Please describe.**
I've had my saved variables folder get corrupted a couple times, and having ajour backups has been a life saver. but I'm still missing the few weeks of tweaks I've done since I remembered to do a backup. 

**Describe the solution you'd like**
A option to select automatic backups. maybe Daily, hourly, or wow close. Allow me to select how much data to allow the backups to store and remove the oldest backups after I've reached that limit.

**Describe alternatives you've considered**
I am currently using the Weak Auras companion application to auto backup my weak auras, and have set reminders to do manual ajour backups.

**Additional context**
Thank you for this fantastic application. I really appreciate how quickly it has come to be such a solid piece of kit in the wow community.

**Comment by tarkah** [comment]
@KyleCRat Thanks for opening the issue! We've had this feature requested in the past #543 and decided against implementation of this since we provide this functionality over command line.

We provide the backup feature over command line ([CLI docs](https://github.com/ajour/ajour/blob/master/CLI.md)), which can be easily automated. For Windows, if you reference the [wiki entry for addon updates](https://github.com/ajour/ajour/wiki/Update-addons-automatically-when-you-log-in-(Windows)), you can easily use the `backup` command instead and achieve backups on interval. You'll still have to prune older backups manually.

**Comment by KyleCRat** [comment]
@tarkah That wiki shows that you also had this functionality for auto updating addons, but saw the value in implementing that feature into the core of the application still. What is the reason behind not feeling that same update for backups would be valuable?
